//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StageInstrument.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_CAMERA_FORMVIEW             101
#define IDD_GRAPH_GRAPH_PROP_PAGE       102
#define IDD_GRAPH_AXIS_PROP_PAGE        103
#define IDD_GRAPH_GRAPHICS_PROPS        104
#define IDP_OLE_INIT_FAILED             105
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDD_GRAPH_CHANGE_TITLE          116
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_StageInstrumentTYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_CLASS_ADD_MEMBER_FUNCTION    132
#define ID_CLASS_ADD_MEMBER_VARIABLE    133
#define ID_CLASS_DEFINITION             134
#define ID_CLASS_PROPERTIES             135
#define ID_NEW_FOLDER                   136
#define ID_SORT_MENU                    137
#define ID_SORTING_GROUPBYTYPE          138
#define ID_SORTING_SORTALPHABETIC       139
#define ID_SORTING_SORTBYTYPE           140
#define ID_SORTING_SORTBYACCESS         141
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDR_PASTE_MENU                  155
#define IDR_WINDOWS_MENU                156
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define ID_VIEW_FILEVIEW                222
#define ID_VIEW_CLASSVIEW               223
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDB_PROPERTIES_HC               312
#define IDR_PROPERTIES                  313
#define IDR_TOOLBAR1                    314
#define IDR_SORT                        314
#define IDR_POPUP_SORT                  316
#define IDB_CLASS_VIEW                  317
#define IDB_CLASS_VIEW_24               318
#define IDB_SORT_24                     319
#define IDR_POPUP_EXPLORER              320
#define IDB_FILE_VIEW                   321
#define IDB_FILE_VIEW_24                322
#define IDB_EXPLORER_24                 323
#define IDR_EXPLORER                    324
#define IDI_CLASS_VIEW_HC               326
#define IDI_FILE_VIEW_HC                328
#define IDI_OUTPUT_WND_HC               329
#define IDI_PROPERTIES_WND_HC           330
#define IDS_FILE_VIEW                   400
#define IDS_CLASS_VIEW                  401
#define IDS_OUTPUT_WND                  402
#define IDS_PROPERTIES_WND              403
#define IDB_ANALYSIS_VIEW               502
#define IDD_MEASURE_SETUP_BOX           503
#define IDD_AUTOMEASURE_BOX             507
#define IDD_MEASURE_PARAMETER_FORMVIEW  511
#define IDB_PNG1                        514
#define IDB_DEVICE_STATUS_HC            514
#define IDC_OPTIONS_TAB                 1000
#define IDC_SLIDER_ZOOM                 1001
#define IDC_SLIDER_INTENSITY            1002
#define IDC_EDIT_INTENSITY              1003
#define IDC_BTN_SAMPLE_1                1004
#define IDC_BTN_SAMPLE_2                1005
#define IDC_BTN_SAMPLE_3                1006
#define IDC_BTN_SAMPLE_4                1007
#define IDC_BTN_SAMPLE_5                1008
#define IDC_BTN_SAMPLE_6                1009
#define IDC_TITLE_BAR                   1011
#define IDC_CANCEL                      1012
#define IDC_STATIC_PERCENT              1013
#define IDC_PROGRESS_MEASURE            1014
#define IDC_STATIC_TIME                 1015
#define IDC_STATIC_TYPE                 1016
#define IDC_XTITLE                      1017
#define IDC_XUOM                        1018
#define IDC_YTITLE                      1019
#define IDC_YUOM                        1020
#define IDC_XAXIS_PRECISION             1021
#define IDC_YAXIS_PRECISION             1022
#define IDC_GRAPH_CHOICE                1023
#define IDC_GRAPH_HIDESHOW              1024
#define IDC_GRAPH_POINTMARKS            1025
#define IDC_GRAPH_MOUSECOORDS           1026
#define IDC_GRAPHS_SHOWALL              1027
#define IDC_GRAPH_TITLE                 1028
#define IDC_GRAPH_CH_TITLE              1029
#define IDC_GRAPH_CH_COLOR              1030
#define IDC_TITLE_STRING                1031
#define IDC_X1                          1032
#define IDC_X2                          1033
#define IDC_Y1                          1034
#define IDC_Y2                          1035
#define IDC_GEN_GRAPH_PROPS_AXIS        1036
#define IDD_MEASURE_PORP_BOX            1037
#define IDC_TAB_MEASURE_OPTIONS         1038
#define IDC_COMBO_MEASURE_RANGE         1039
#define IDC_EDIT_LENGTH                 1040
#define IDC_EDIT_DURATION               1041
#define IDC_EDIT_FORCE                  1042
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_OPEN                         32771
#define ID_OPEN_WITH                    32772
#define ID_DUMMY_COMPILE                32773
#define ID_PROPERTIES                   32774
#define ID_BTN_START                    32775
#define ID_BTN_PAUSE                    32777
#define ID_BTN_STOP                     32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        515
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           600
#endif
#endif
