/*
 * Generated by erpcgen 1.11.0 on Wed Jan 31 00:53:05 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_StepProfilerInterface_h_)
#define _StepProfilerInterface_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "infra/erpc_version.h"

#if 11100 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS_STEPPROFILERINTERFACE)
#define ERPC_TYPE_DEFINITIONS_STEPPROFILERINTERFACE

#endif // ERPC_TYPE_DEFINITIONS_STEPPROFILERINTERFACE

/*! @brief StepProfiler identifiers */
enum _StepProfiler_ids
{
    kStepProfiler_service_id = 1,
    kStepProfiler_Z_Home_id = 1,
    kStepProfiler_Y_Home_id = 2,
    kStepProfiler_Z_Run_id = 3,
    kStepProfiler_Y_Run_id = 4,
    kStepProfiler_setForce_id = 5,
    kStepProfiler_getLVDTStatus_id = 6,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name StepProfiler
//@{
void Z_Home(void);

void Y_Home(void);

void Z_Run(int32_t dir);

void Y_Run(int32_t dir);

void setForce(int32_t force);

int32_t getLVDTStatus(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _StepProfilerInterface_h_
